config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only:[:create, :new, :show]
  resource :session, only:[:new, :create, :destroy]
  resources :bands
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, :session_token, :password_digest, presence: true
  validates :password, length:{ minimum: 6, allow_nil: true }

  attr_reader :password
  after_initialize :ensure_session_token

  def self.find_by_credentials(email, password)
    @user = User.find_by(email: email)
    if @user && @user.is_password?(password)
      @user
    else
      nil
    end
  end

  def self.generate_session_token
    self.session_token = SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?
  
  def login!(user)
    session[:session_token] = user.reset_session_token!
  end
  
  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end
  
  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def new
    @band = Band.new
  end

  def index
    @bands = Band.all
  end

  def create
    @band = Band.new(band_params)
    if @band.save!
      redirect_to bands_url 
    else
      @band.errors.full_messages
    end
  end

  def show
    @band = Band.find(params[:id])
  end

  def edit
    @band = Band.find(params[:id])
  end
  
  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to bands_url
    else
      @band.errors.full_messages
    end

  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url    
  end


  private
  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_credentials(
        params[:user][:email], 
        params[:user][:password]
      )

    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save!
      login!(@user)
      redirect_to user_url(@user)
    else
      render :new
    end
  end
  
  def show
    @user = User.find(params[:id])
    # redirect_url user_url(@user)
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token_input
    "<input type='hidden' name='authenticity_token' value='#{ form_authenticity_token }'>".html_safe
  end
end

app/views/bands/_form.html.erb
<% if type == :new %>
  <% action_url = bands_url %>
<% else %>
  <% action_url = band_url %>
<% end %>

<form action=" <%= action_url %> " method="post">
  <% if type == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  
  <%= auth_token_input %>

  <label>Name:<br>
    <input type="text" name="band[name]">
  </label>
  <br>
  <br>
  <input type="submit" value="Submit">
</form>

app/views/bands/edit.html.erb
<h2>
  Update the Band
</h2>

app/views/bands/index.html.erb
<h2>
  All Bands
</h2>

<ul>
  <% @bands.each do |band| %>
    <a href="/bands/<%= band.id %>"><%= band.name %></a>
    <br>
  <% end %>
</ul>

app/views/bands/new.html.erb
<h2>
  Add a Band
</h2>

<form action=" <%= bands_url %> " method="post">
  <%= auth_token_input %>
  <label>Name:<br>
    <input type="text" name="band[name]">
  </label>
  <br>
  <br>
  <input type="submit" value="Submit">
</form>

<%= render 'form', band: @band, type: new %>

app/views/bands/show.html.erb
<h2>
  <%= @band.name %>
</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <style>
    h1 {
      font-family: Geneva;
    }

    header {
      display: flex;
      justify-content: space-between;
    }

    header > h1{
      color: white;
      display: flex;
      justify-content: flex-start;
    }

    header > a{
      display: flex;
      justify-content: right;
      height: 100%;
      background-color: grey;
      color: white;
      border-radius: 5px;
      padding: 5px;
    }

    body {
      
      margin: 0 auto;
      width: 60%;
      color: white;
      background-image: url('https://steamuserimages-a.akamaihd.net/ugc/952958387206892057/50677EFA11070FB2DBAA9B813038900EFC24819C/');
      background-size: cover;
    }

    .main {
      background-color: rgba(250, 235, 215, 0.411);
    }

  </style>



  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>Music App</h1>
      <% if logged_in? %>
        <form action="<%= session_url %>" method="post">
          <%= auth_token_input %>
          
          <%= auth_token_input %>
          <input type="hidden" name="_method" value="delete">
          <input type="submit" value="Logout">
        </form>
      <% else %>
          <a href=" <%= new_user_url %> ">Sign Up</a>
          <a href=" <%= new_session_url %> ">Sign In</a>
      <% end %>
    </header>
    <div class="main">
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<form action="<%= users_url %>" method="post">
  <%= auth_token_input%>
  <label>Email:
    <input type="text" name="user[email]">
  </label>

  <label>Password:
    <input type="password" name="user[password]">
  </label>

  <input type="submit" value="Sign Up">
</form>

app/views/users/show.html.erb
<h2>Welcome back!</h2>
<%= @user.email %>